### ISSUE TITLE
هوش مصنوعی فرادرس

### ISSUE THREAD

**Issue by ParSal123** [ssadras/V.P.V.A-ver-ANNA#2]
سلام
من توی فایل‌هام گشتم یه آشنایی با هوش مصنوعی از فرادرس پیدا کردم که 25 قسمته. شما هم همون رو دارید می‌بینید؟

پ.ن. ریپوزیتوریتون عوض شده؟ آخرین کامیت اینجا تقریبا مال ماه پی‌شه

**Comment by ssadras** [comment]
سلام. نه مال من ۱۲ قسمتهاست.
راستش خیلی وقته که داریم بدون گیت کار میکنیم چون بیشتر در حال یادگیری هستیم
ولی ری\وزیستوری همون هست و به زودی کامنت ها جدید رو میذاریم.
با تشکر.
